- name: Copy environment file to remote host
  ansible.builtin.copy:
    src: "{{ env_file_location }}"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{given_directory}}/.env"
    mode: '0644'  # Optional file permissions
    owner: "{{ sudo_user }}"  # Optional ownership
    group: "{{ sudo_user }}"  # Optional group ownership
    force: true
    backup: true
  vars:
     # Fallback to 'root' if SUDO_USER is not set
    sudo_user: "{{ ansible_env.SUDO_USER | default('root') }}"
    env_file_location: "{{lookup('ansible.builtin.env', 'REACTIVE_RESUME_ENV_FILE')}}" 