- name: Copy config files to remote host
  hosts: usa4foryou-server
  vars:
    registerable_domain: "{{ lookup('ansible.builtin.env', 'REGISTERABLE_DOMAIN') }}"
  tasks:
    - name: Copy homepage files
      ansible.builtin.import_role:
        name: homepage
        tasks_from: copy_files
    - name: Copy traefik files
      ansible.builtin.import_role:
        name: traefik
        tasks_from: copy_files