- name: Copy config files to remote host
  hosts: test-ubuntu
  vars:
    registerable_domain: "{{ lookup('ansible.builtin.env', 'REGISTERABLE_DOMAIN') }}"
  tasks:
    - name: Copy homepage files
      ansible.builtin.import_role:
        name: homepage_deploy
        tasks_from: copy_files
    - name: Copy traefik files
      ansible.builtin.import_role:
        name: traefik_deploy
        tasks_from: copy_files