- name: Install qemu guest agent
  hosts: test-ubuntu
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Ensure qemu guest agent is installed
      ansible.builtin.apt:
        name: qemu-guest-agent
        update_cache: yes
        state: present