---
# - name: Install Docker on all Machines
#   hosts: all
#   become: true
#   roles:
#     - role: docker_install
#       tags:
#         - install
#         - docker

# - name: Cofigure pihole containers
#   hosts: pihole
#   become: true
#   roles:
#     - role: pihole_deploy
#       tags:
#         - deploy
#         - pihole
#     - role: traefik_deploy
#       tags:
#         - deloy
#         - traefik
#     - role: homepage_deploy
#       tags:
#         - deploy
#         - homepage

# - name: Install Nebula Sync
#   hosts: docker-on-main
#   become: true
#   roles:
#     - role: nebula-sync_deploy
#       tags:
#         - deloy
#         - nebula-sync


# - name: Setup databases
#   hosts: databases
#   become: true
#   roles:
#     - role: minio_deploy
#       tags:
#         - deploy
#         - minio
#     - role: mariadb_deploy
#       tags:
#         - deploy
#         - mariadb

# - name: Setup jenkins on main VM for docker apps
#   hosts: main-docker-apps
#   become: true
#   roles:
#     - role: jenkins_deploy
#       tags:
#         - deploy
#         - jenkins

# - name: Setup jenkins agent on agent vm
#   hosts: jenkins-agent
#   become: true
#   roles:
#     - role: jenkins_agents_deploy
#       tags:
#         - deploy
#         - jenkins-agent

- name: Back up main data to external hdd
  hosts: ubuntu-with-gpu
  become: true
  roles:
    - role: backup_main_data
      tags:
        - backup
        - main-data

- name: Expand storage on ubuntu with gpu 
  hosts: ubuntu-with-gpu
  become: true
  tasks:
    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sdb
        number: "{{ sdb_info.partitions | length }}"
        part_end: "100%"
        resize: true
        state: present
      register: sdb_info
      when: sdb_info.partitions | length > 0
      tags: expand-storage