---
- hosts: "{{ lookup('ansible.builtin.env', 'HOSTS') }}"
  gather_facts: true
  vars:
    mount_point: "{{ lookup('ansible.builtin.env', 'MOUNT_POINT') }}"
    disk_device: "/dev/{{ lookup('ansible.builtin.env', 'DISK_NAME') }}"
    partition_device: "/dev/{{ lookup('ansible.builtin.env', 'PARTITION_NAME') }}"
    partition_uuid: "{{ lookup('ansible.builtin.env', 'PARTITION_UUID') }}"
    registerable_domain: "{{ lookup('ansible.builtin.env', 'REGISTERABLE_DOMAIN') }}"
    undeploy: "{{ lookup('ansible.builtin.env', 'UNDEPLOY') | default('false') | bool }}"
  roles:
    - role: unmount_drive_by_uuid
      tags: 
        - never
        - unmount_by_uuid
    - role: expand_storage
      tags: 
        - never
        - expand_storage
    - role: backup_main_data
      tags:
        - never
        - copy_main_data
      vars:
        to_place: "{{ mount_point }}"
        from_place: "{{ lookup('ansible.builtin.env', 'FROM_PLACE') }}"
    - role: mount_drive_by_uuid
      tags: 
        - never
        - mount_by_uuid
    - role: mount_drive_by_partition
      tags: 
        - never
        - mount_by_partition
    - role: unmount_drive_by_partition
      tags: 
        - never
        - unmount_by_partition
    - role: docker_install
      tags:
        - never
        - docker-install
        - docker_install
    - role: ollama
      tags:
        - never
        - ollama
    - role: traefik
      tags:
        - never
        - traefik
    - role: homepage
      tags:
        - never
        - homepage
    - role: reactive_resume
      tags:
        - never
        - reactive_resume
        - reactive-resume
    - role: wireguard_install
      tags:
        - never
        - wireguard-install
        - wireguard_install
  tasks:
    - ansible.builtin.import_role:
        name: traefik
        tasks_from: copy_files
      vars:
        registerable_domain: "{{ lookup('ansible.builtin.env', 'REGISTERABLE_DOMAIN') }}"
        external_facing: true
      tags: 
        - never
        - traefik-copy-files


  