---
- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-directory-files

- name: Copy services file
  ansible.builtin.template:
    src: "config/services.j2"
    dest: "{{ ansible_env.HOME }}/docker-compose/{{ given_directory }}/config/services.yaml"
    mode: '0755'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-file

- ansible.builtin.import_role:
    name: common
    tasks_from: compose-up
