---
- name: Install WireGuard from the official repository
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - wireguard-tools
    - iptables

- name: Generate WireGuard private key
  ansible.builtin.command: wg genkey
  register: wireguard_private_key
  changed_when: false
- name: Generate WireGuard public key
  ansible.builtin.shell: "echo {{ wireguard_private_key.stdout }} | wg pubkey"
  register: wireguard_public_key
  changed_when: false

- name: Create WireGuard configuration directory
  ansible.builtin.file:
    path: "/etc/wireguard"
    state: directory
- name: Save WireGuard private key
  ansible.builtin.copy:
    content: "{{ wireguard_private_key.stdout }}"
    dest: "/etc/wireguard/privatekey"
    mode: '0600'
- name: Save WireGuard public key
  ansible.builtin.copy:
    content: "{{ wireguard_public_key.stdout }}"
    dest: "/etc/wireguard/publickey"
    mode: '0644'
