- name: Copy homepage config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'  # Optional file permissions
    owner: "{{ sudo_user }}"  # Optional ownership
    group: "{{ sudo_user }}"  # Optional group ownership
  vars:
     # Fallback to 'root' if SUDO_USER is not set
    sudo_user: "{{ ansible_env.SUDO_USER | default('root') }}"
  loop:
    - { src: 'config/services.j2', dest: '{{ ansible_env.PWD }}/docker-compose/{{given_directory}}/config/services.yaml' }

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-directory-files