---
- ansible.builtin.import_role:
    name: common
    tasks_from: check-docker

# - ansible.builtin.import_role:
#     name: common
#     tasks_from: create-compose-directory

# - ansible.builtin.import_role:
#     name: common
#     tasks_from: copy-compose-file

- name: Log environment variables
  ansible.builtin.debug:
    msg: "{{lookup('ansible.builtin.env', 'REACTIVE_RESUME_ENV_FILE')}}"

- name: save environment variables to file
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.env', 'REACTIVE_RESUME_ENV_FILE') }}"
    dest: "{{ ansible_env.PWD }}/env"
    mode: '0644'
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"    

- name: check environment variables
  ansible.builtin.assert:
    that:
      - ansible_env.PWD is defined
      - ansible_env.SUDO_USER is defined
    fail_msg: "Required environment variables are not set: PWD or SUDO_USER"