---
- ansible.builtin.import_role:
    name: common
    tasks_from: check-docker

- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory

- ansible.builtin.import_tasks:
    file: copy_files.yaml   

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-file

- ansible.builtin.import_role:
    name: common
    tasks_from: compose-up