---
- ansible.builtin.import_role:
    name: common
    tasks_from: check-docker
  when: undeploy == false

- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory
  when: undeploy == false

- ansible.builtin.import_tasks:
    file: copy_files.yaml
  when: undeploy == false

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-file
  when: undeploy == false

- ansible.builtin.import_role:
    name: common
    tasks_from: compose-up
  when: undeploy == false

- ansible.builtin.import_role:
    name: common
    tasks_from: compose-down
  when: undeploy == true

- ansible.builtin.import_role:
    name: common
    tasks_from: remove-compose-directory
  when: undeploy == true