---
- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/sdb unit=MiB
  register: sdb_info

- name: Remove all partitions from disk
  community.general.parted:
    device: /dev/sdb
    number: '{{ item.num }}'
    state: absent
  loop: '{{ sdb_info.partitions }}'

- name: Create a new ext4 primary partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    # part_end: "100%"
    state: present
    fs_type: ext4

# - name: Extend an existing partition to fill all available space
#   community.general.parted:
#     device: /dev/sdb
#     number: 1
#     resize: true
#     state: present