---
- name: Extend an existing partition to fill all available space
  community.general.parted:
    device: "{{ disk_device }}"
    number: 1
    label: gpt
    part_end: "100%"
    resize: true
    state: present

- name: "running e2fsck on {{ partition_device }} before resizing"
  ansible.builtin.shell: |
    "e2fsck -fy -a {{partition_device}} || true"
  register: e2fsck_result
  ignore_errors: true

- name: Result of e2fsck
  debug:
    msg: "{{ e2fsck_result.stdout }}"
  when: e2fsck_result is defined

- name: "Resize the filesystem on {{ partition_device}}"
  community.general.filesystem:
    fstype: ext4
    dev: "{{ partition_device }}"
    resizefs: true