---
- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/sdb unit=MiB
  register: sdb_info

# - name: Remove all partitions from disk
#   community.general.parted:
#     device: /dev/sdb
#     number: '{{ item.num }}'
#     state: absent
#   loop: '{{ sdb_info.partitions }}'

# - name: Create a new ext4 primary partition
#   community.general.parted:
#     device: /dev/sdb
#     number: 1
#     state: present
#     fs_type: ext4
#     flags: [ lvm ]
#     label: gpt
#     part_end: "100%"

# - name: Create a ext4 filesystem on /dev/sdb1
#   community.general.filesystem:
#     fstype: ext4
#     dev: /dev/sdb1

- name: Extend an existing partition to fill all available space
  community.general.parted:
    device: /dev/sdb
    number: 1
    label: gpt
    part_end: "100%"
    resize: true
    state: present

- name: run e2fsck on /dev/sdb1
  community.builtin.command: "e2fsck -f  -a /dev/sdb1"

- name: Resize the filesystem on /dev/sdb1
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb1
    resizefs: true