---
- name: Printing mount point variable value from environment
  ansible.builtin.debug:
    msg: "Mount point is {{ lookup('ansible.builtin.env', 'MOUNT_POINT') }}"
- name: Printing mount point variable value from local variable
  ansible.builtin.debug:
    msg: "Mount point is {{ mount_point }}"
- name: "Check if {{ mount_point }} is mounted from main task"
  include_role:
    name: check_mount_point
  register: mount_check

- name: Print mount check result from main task
  ansible.builtin.debug:
    var: mount_check