---
- name: "Check if {{ partition_uuid }} is mounted from main task"
  include_role:
    name: check_mount_point
  register: mount_check

# - name: "Unmount {{ mount_point }}"
#   ansible.posix.mount:
#     path: "{{ mount_point }}"
#     src: "UUID={{ partition_uuid }}"
#     fstype: ext4
#     state: unmounted