---
- name: "Unmount {{ mount_point }} if it is mounted"
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "UUID={{ partition_uuid }}"
    fstype: ext4
    state: unmounted
  when: is_mounted == true