---
- name: Check if {{ mount_point }} is mounted
  include_role:
    name: check_mount_point
  vars:
    mount_point: "{{ mount_point }}"
  register: mount_check

- name: Print mount check result
  ansible.builtin.debug:
    var: mount_check