---
- name: Copy Docker Compose file and notify compose
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}/docker-compose.yaml"
    mode: '0755'  # Optional file permissions
    owner: "{{ sudo_user }}"  # Optional ownership
    group: "{{ sudo_user }}"  # Optional group ownership
  vars:
     # Fallback to 'root' if SUDO_USER is not set
    sudo_user: "{{ ansible_env.SUDO_USER | default('root') }}"
  notify:
    - Restart Docker Compose