- name: "Copy {{ src_folder }} folder to remote host {{ given_directory }} directory"
  ansible.builtin.copy:
    src: "{{ src_folder }}"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}"
    mode: '0755'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership