---
- name: Copy Docker Compose file and notify compose
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}/docker-compose.yaml"
    mode: '0755'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership
  notify:
    - Start Docker Compose