- name: "Copy {{ src_folder }} folder to remote host {{ given_directory }} directory"
  ansible.builtin.copy:
    src: "{{ src_folder }}"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}"
    mode: '0755'  # Optional file permissions
    owner: "{{ sudo_user }}"  # Optional ownership
    group: "{{ sudo_user }}"  # Optional group ownership
  vars:
     # Fallback to 'root' if SUDO_USER is not set
    sudo_user: "{{ ansible_env.SUDO_USER | default('root') }}"