---
- name: "Create {{ given_directory }} directory"
  ansible.builtin.file:
    path: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: "{{ sudo_user }}"  # Optional ownership
    group: "{{ sudo_user }}"  # Optional group ownership
  vars:
    sudo_user: "{{ ansible_env.SUDO_USER }} | default('root') # Fallback to 'root' if SUDO_USER is not set"