---
- name: "Setup {{ given_directory }} directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/docker-compose/{{ given_directory }}"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership