---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
