---
- name: Set mounts fact
  ansible.builtin.set_fact:
    mounts: "{{ ansible_mounts | map(attribute='mount') | list }}"

- name: Print mounts fact
  ansible.builtin.debug:
    var: mounts

- name: Check if {{ mount_point }} is in mounts list
  ansible.builtin.set_fact:
    is_mounted: "{{ mount_point in mounts }}"

- name: Print mount check result
  ansible.builtin.debug:
    var: is_mounted
- name: Check if external hard drive is mounted
  ansible.builtin.debug:
    msg: "External hard drive is mounted"
  when: is_mounted == true
- name: Check if external hard drive is not mounted
  ansible.builtin.debug:
    msg: "External hard drive is not mounted"
  when: is_mounted == false