---
- name: Set mounts fact
  ansible.builtin.set_fact:
    mounts: "{{ ansible_mounts | map(attribute='mount') | list }}"

- name: Check if {{ mount_point }} is in mounts list
  ansible.builtin.set_fact:
    mount_check: "{{ mount_point in mounts['mount'] }}"

- name: Print mount check result
  ansible.builtin.debug:
    var: mount_check
- name: Check if external hard drive is mounted
  ansible.builtin.debug:
    msg: "External hard drive is mounted"
  when: mount_check.rc == 1
- name: Check if external hard drive is not mounted
  ansible.builtin.debug:
    msg: "External hard drive is not mounted"
  when: mount_check.rc == 0