---
- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory

- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory
  vars:
    given_directory: traefik/data

- ansible.builtin.import_role:
    name: common
    tasks_from: create-compose-directory
  vars:
    given_directory: traefik/configs

- name: Copy acme.json file to remote host
  ansible.builtin.copy:
    src: data/acme.json
    dest: "{{ ansible_env.PWD }}/docker-compose/traefik/data/acme.json"
    mode: '0600'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership
    force: no
    backup: true

- name: Copy traefik static config files to remote host
  ansible.builtin.template:
    src: "templates/traefik.yml.j2"
    dest: "{{ ansible_env.PWD }}/docker-compose/{{ given_directory }}/data/traefik.yml"
    mode: '0755'  # Optional file permissions
    owner: "{{ ansible_env.SUDO_USER }}"  # Optional ownership
    group: "{{ ansible_env.SUDO_USER }}"  # Optional group ownership

- ansible.builtin.import_role:
    name: common
    tasks_from: copy-compose-file

- ansible.builtin.import_role:
    name: common
    tasks_from: compose-up