---
# - name: Update known_hosts
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: make_host_known

# - name: mount external hard drive
#   ansible.posix.mount:
#     path: /mnt/externalhdd
#     src: "UUID={{ lookup('ansible.builtin.env', 'EXTERNAL_HDD_UUID') }}"
#     fstype: ext4
#     state: mounted

- name: Create backup directory based on current date {{ ansible_date_time.date }}
  ansible.builtin.file:
    path: "{{to_place}}/backup/{{ ansible_date_time.date }}"
    state: directory

- name: Copy main data to external hard drive
  ansible.builtin.command: "sudo rsync -rhviuat --exclude 'appdata*/' --exclude '*trashbin*/' --exclude '*thumbnails/' {{from_place}} {{to_place}}/backup/{{ ansible_date_time.date }}/"
  # ansible.posix.synchronize:
  #   src: /mnt/maindata/botir/uploads/
  #   dest: "/mnt/externalhdd/backup/{{ ansible_date_time.date }}/botir/uploads/"
  #   rsync_opts:
  #     - "--exclude=appdata*/"
  #     - "--exclude=*trashbin*/"
  #     - "--exclude=*thumbnails/"
  register: rsync_result
- name: Print rsync result
  ansible.builtin.debug:
    var: rsync_result
- name: Check if rsync was successful
  ansible.builtin.debug:
    msg: "Rsync was successful"
  when: rsync_result.rc == 0


